// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gilhucuxjtrovstoqrui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpbGh1Y3V4anRyb3ZzdG9xcnVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyODkyNzgsImV4cCI6MjA3MDg2NTI3OH0.Qu4CSHlGgMozGokz9QbTs5JaD7cfeZcFeVr3WhxliOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});